# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: modelm
    snippets:
      - studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: modelm
  - board: modelm
    snippets:
      - studio-rpc-usb-uart
      - zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: modelm_logging
  - board: modelm
    shield: settings_reset
    artifact-name: modelm_reset
  - board: modelm_v4
    snippets:
      - studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: modelm_v4
  - board: modelm_v4
    snippets:
      - studio-rpc-usb-uart
      - zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: modelm_v4_logging
  - board: modelm_v4
    shield: settings_reset
    artifact-name: modelm_v4_reset
  - board: nice_nano_v2
    shield: model_x
    snippets:
      - studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: model_x
  - board: nice_nano_v2
    shield: model_x
    snippets:
      - studio-rpc-usb-uart
      - zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: model_x_logging
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: model_x_reset
